server:
  port: 8080
  contextPath: /customer-service-jdg
spring:
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
    jmx:
      enabled: true
#  cache:
#    type: infinispan
#    infinispan:
#      config: local-cache-config.xml
  session:
    store-type: none
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
#infinispan:
#  remote:
#    enabled: true
#    server-list: 192.168.99.100:11222
#    client-properties: hotrod-client.properties
logging:
  level:
    org:
      jgroups:
        protocols: WARN